label chapter2_1:
    $ chapter("CHAPTER 2\nPART 1: SID")
    
    scene sound only with fastDissolve
    play music "audio/BGMusic/escalation.wav"
    defMin "What?![pause] Wherever Aegis covers belongs to the jurisdiction of the metropolis MD.[pause] No doubt about it."
    defMin "Who are you to take over the command?"
    defMin "If you can't bring up any convincing reasons, I will never remove the MPD blockade!"
    milOff "It's top secret.[pause] I have no right or duty to brief you!"
    milOff "Now, the military has taken charge of this.[pause]\nPlease cooperate!"
    defMin "No way![pause] This operation is led by MD![pause]\nUnless you have the Senate's Executive Order..."
    female "Heh, you two..."
    female "How could you be still wasting time on trivial things?"
    milOff "The voice is from--\nMariru... Officer Mariru?"
    milOff "Officer Mariru!"
    mariru "Skip the salute.[pause] SID has long been independent from the military."
    defMin "Mariru... Humph!"
    defMin "This is a category-4 encrypted communication![pause]\nHow could you..."
    mariru "Never mind the trivial details![pause]\nLet's focus on the problems at hand!"
    mariru "As we are on category-4 encryption, I'll just get to the point--"
    mariru "Brief me all the intelligence you've got!"
    milOff "Ahh, yes, Ma'am!"
    milOff "The monitoring systems around the Research Center have received lots of disturbances.[pause] A"
    milOff "large-scale abnormal Spacetime Flux has been detected..."
    defMin "Spacetime Flux?[pause]\nIt means..."
    mariru "The Crisis Response Code of the Academy City has made it very clear, hasn't it..."
    mariru "Or, even MD has no access since the Code is confidential?"
    defMin "Er... Could it be...\nRelated to the mishandling of Substance H..."
    mariru "And the sudden disappearance of the Ross Goblet..."
    mariru "... It's been six years since the last crisis like this."
    mariru "We have to get prepared for the worst--"
    defMin "I... I see..."
    defMin "We must immediately lift the inner blockade, and evacuate under the cover of a drill..."
    mariru "Excellent.[pause] How is the military deployment at the outer ring?"
    milOff "Special operation teams are deploying heavy firepower within 2 km of the flux site,"
    milOff "but we still can't identify the level of threat."
    mariru "What about the media control?"
    milOff "C-13 script is being executed as per protocol."
    mariru "Good.[pause] From now on, SID takes charge of the central flux area."
    mariru "You guys must move now!"
    milCom "Yes!"
    defMin "Al... alright then...\nTake care."

    jump chapter2_2