
label chapter2_5:
    $ chapter("CHAPTER 2\nPART 5: Test Subject")
    
    scene empty room with fastDissolve
    play music "audio/BGMusic/abnormal.wav"
    sayadd marirusid neutral "Since this morning, we have received several alarms of sudden Spacetime Fluxes in New Opulentia."
    sayswap marirusid frown "It's like something was activated last night..."
    sayswap marirusid "Satellite imagery shows that you disappeared at one spot within the flux area, and showed up out"
    sayswap marirusid "of nowhere at another spot not long after, together with someone else."
    sayswap narrator "Mariru turns to Annie."
    sayswap marirusid neutral "Where you showed up, the flux automatically stopped."
    sayadd playerbat confused "The flux area?[pause] You mean the Research Center?"
    sayswap marirusid neutral "Yup."
    sayswap playerbat fakecheer "Could it be machine failure?[pause] I had never left the street."
    sayswap narrator "The look in Mariru's face hardened."
    sayswap marirusid frown "Do you think anyone can enter or leave the Spacetime Flux area as they like?"
    sayswap playerbat worry "The flux... Is it really that mighty?"
    sayswap marirusid neutral "You really know nothing, do you?"
    marirusid "Spacetime is fundamental in physics.[pause] It's like the coordinate system of our universe.[pause] No matter"
    marirusid "how particles move within the system, the coordinate system must remain stable."
    marirusid "If it shifts, even in the slightest jitter, it will be devastating to the order of the particles within it."
    sayswap marirusid smile "Let's say if 5%% of the particles of a building shift randomly just by 1 micrometer, then the"
    marirusid "material structure will be completely destroyed and the building immediately collapse."
    sayswap marirusid neutral "But you are perfectly fine now, and the buildings within the flux area are intact."
    sayswap marirusid frown "(Research on the Divine Touch shows that humans with \"GHOST\" are unable to enter the flux area)"
    sayswap marirusid neutral "In a word, it's like you were placed in the eye of a Category 5 hurricane,"
    marirusid "came out intact, and even quieted the storm."
    sayswap playerbat confused "..."
    sayswap playerbat neutral "Could the flux be caused by those who attacked me?"
    playerbat "They seemed insane..."
    sayswap marirusid neutral "Hang on![pause] I have to brief the Senate now--"
    marirusid "There's this creepy guy among them who likes to run lie-detector tests at conference calls.[pause] So, the"
    marirusid "little I know now the better."
    sayswap playerbat fakecheer "Your comments on the Senate... are really an eye-opener."
    sayswap marirusid talk "And girls should know when to lie~"
    sayswap playerbat fear "I'm not a girl!"
    sayswap playerbat dissatisfied "Alright, I'll keep it to myself..."
    sayswap marirusid neutral "In recent years, there are only four Spacetime Fluxes recorded globally."
    marirusid "They're mostly related to the mishandling of Substance H."
    sayswap marirusid smile "When an unknown Divine Touch is suddenly activated, catastrophic results are very likely to follow."
    sayswap playerbat shock "... Were there any people hurt?"
    sayswap marirusid frown "In the most severe incident, there were tens of thousands of casualty."
    marirusid "But Academy Cities would speak with one voice and tone them down as \"regular incidents\"..."
    sayswap marirusid neutral "Gas leaks, air crashes, terrorist attacks, and so on..."
    sayswap playerbat shadow "So, this time..."
    sayswap marirusid neutral "This one is different.[pause] There've never been successive fluxes at such a scale..."
    sayswap marirusid smile "So severe that it goes beyond the imagination of our highest-level propaganda.[pause] So, we'll literally"
    marirusid "run out of lies..."
    sayswap playerbat shock "Is it because of me?[pause]\nIf there is anything I can do..."
    sayswap marirusid talk "Oh, cut it.[pause] Your body transformation might have something to do with the crisis, but you alone"
    marirusid "are impossible to cause such a disaster."
    sayswap marirusid neutral "If you really want to find clues, I can arrange my men to take you to the site."
    sayswap marirusid smile "(If it's true, then she might be the only solution...)"
    sayswap marirusid lecture "But, never push yourself too hard, and don't mention anything about your body.[pause] Is that clear?"
    sayswap playerbat worry "No mention of my body...[pause] Did you mean...[pause]\nI have to pretend I've always been a girl?"
    sayswap marirusid smile "You know...\nThe supremacy of science has been at the heart"
    marirusid "of New Opulentia's governance."
    sayswap marirusid talk "If your experience goes public, you'll be seen as a \"guinea pig\" and taken to a research institution!"
    sayswap marirusid smile "I bet lots of men vowing to devote themselves to science would line up to study your body..."
    marirusid "As it's rare to have an experimental subject as cute as you--"
    sayswap playerbat shadow "... I... I see!"
    playerbat "I... I will keep my mouth shut!"

    jump chapter2_6