
label chapter2_6:
    $ chapter("CHAPTER 2\nPART 6: Emergency")
    
    scene blue data with fastDissolve
    play music "audio/BGMusic/ominous magic.wav"

    sayadd marirusid neutral "(Muttering) It's obviously more interesting to talk with that little kid..."
    sayswap narrator "An audio call notice pops up on the screen in the side-front of Mariru.[pause] The gender of the speaker"
    narrator "is unknown as the voice is masked as a robotic voice."
    sayswap marirusid neutral "(After countless briefings, this one-way encrypted modulation still feels so annoying.)"
    sayswap kirs "So, about the disappearance of the Ross Goblet, how is the investigation going?"
    sayswap marirusid smile "At 00:15 after midnight today, the security staff noticed the Ross Goblet disappeared."
    marirusid "At 06:40, the True Sight Satellite Monitoring System detected strong dimensional warps and"
    marirusid "sent out a warning."
    marirusid "Since 07:00, the Aegis System has received six Spacetime Flux alarms within New Opulentia."
    marirusid "There have been 32 similar alarms within a 1,500 km radius of the Research Center."
    sayswap kirs "These are all documented.[pause] Get straight to your conclusion."
    sayswap narrator "Mariru looks back to the right and beams a smile."
    narrator "Just from the sedate tone, she can tell it's the Chief Executive of the Senate."
    sayswap marirusid frown "--This is not a case of theft.[pause] It's the activation of Substance H and the resulting effects."
    marirusid "I can't tell if it's a meme Substance H from its frequency and scale."
    sayswap narrator "As Mariru pauses, sounds of astonishment, followed by chatters, come out of the black screens around her."
    narrator "!"
    sayswap kirs "What?!"
    sayswap narrator "A deep, low voice comes from the left side."
    sayswap bright "You mean the exponential outburst of the psychoactive Divine Touch?"
    bright "Interesting..."
    sayswap marirusid frown "For now it looks more like a simultaneous outburst of independent incidents."
    marirusid "As to the \"Divine Touch\" you mentioned--I don't like using this laymen term."
    sayswap marirusid smile "(He is an authority in the area of psychoactive Substance H...)"
    marirusid "(Although I always think this gorilla man's brain is damaged due to overexposure to radiation.)"
    sayswap bright "What do you make of it then..."
    sayswap marirusid neutral "I cannot make any conclusion yet due to the lack of useful information."
    marirusid "At this point, I ask your permission of a Class-S search warrant.[pause] Your understanding is appreciated."
    sayswap narrator "Mariru ignores the murmurs surrounding her, and focuses on her hand-held device."
    sayswap marirusid smile "(The kid went to another flux area...)"
    marirusid "(See![pause] She disappeared and re-appeared after a while, and the flux nearby stopped.)"
    sayswap marirusid frown "(In the on-site video clip... Is that blood on her body?)"
    marirusid "(The little idiot... She can't be...)"
    sayadd kirs "You seem to have other concerns."
    sayswap marirusid neutral "What?...[pause] No, nothing."
    sayswap kirs "What were you looking at?[pause] Is it more important than the briefing?"
    sayswap marirusid "talk ... Nah, just a funny kitty video.[pause] You wanna have a look?"
    sayswap kirs "!"
    sayswap narrator "A high-pitched buzzing comes out from the left side of Mariru."
    sayswap marirusid neutral "Don't get mad.[pause] Relaxation boosts productivity."
    sayswap kirs "..."
    saydrop kirs narrator "Mariru looks around.[pause] No one seems to notice her hesitation."
    sayadd marirusid neutral "That's all I have, sir.[pause]\nThe investigation is ongoing."
    sayswap marirusid smile "If you have no more questions, I'd better go to the flux site now."
    sayswap narrator "When Mariru is about to leave, a giddy voice comes from her left."
    sayswap sharpc "... I've been told that your men took two teenagers to SID for inquiry.[pause] Is that right?"
    sayswap marirusid neutral "...\n(The annoying one again)"
    sayadd sharpc "Is there anything special with them?[pause] Officer...[pause]\nOops, sorry--Dr.[pause] Mariru."
    sayswap marirusid neutral "... Nothing special.[pause] I just got confirmation that these two kitties broke into the blocked area out of curiosity."
    marirusid "I'll have my men see them home."
    sayswap sharpc "Is that so?[pause] All right."
    sharpc "At such a sensitive timing, I hope they won't be seen by other countries as something strange..."
    sayswap narrator "These words immediately arouse discussions among others."
    narrator "... What does that mean?"
    sayswap sharpc "My casual remark may make you uncomfortable."
    sharpc "Sorry for that.[pause] Just ignore me."
    saydrop sharpc marirusid smile "...\n(So annoying.)"
    sayswap bright "Anyway, the crisis has already attracted attention from other Academy Cities."
    bright "We count on you for the secret investigations and public opinion shaping."
    sayswap marirusid neutral "Will do."

    jump chapter2_7